### ISSUE TITLE
best way to cite?

### ISSUE THREAD

**Issue by brookehus** [MobleyLab/basic_simulation_training#101]
Would you be able to provide (maybe in a readme?) the best way to cite the article, perhaps as an example latex bib entry?

If this already exists, I couldn't find it - thanks!

**Comment by brookehus** [comment]
We are in the process of submitting revisions to our own LiveCoMS article within a couple of days. So of course we can update the github with the proper citation when it comes. But it would be cool to have the LiveCoMS one if possible!

**Comment by brookehus** [comment]
Great - thank you!

**Comment by davidlmobley** [comment]
@brookehus you can use the DOI 10.33011/livecoms.1.1.5957 I am told.
