### ISSUE TITLE
But generally, the autocorrelation time isn't known beforehand.  

### ISSUE THREAD

**Issue by mrshirts** [MobleyLab/basic_simulation_training#107]
https://github.com/MobleyLab/basic_simulation_training/blob/924ee8724dca2462c12f6f1dbc287b5f1007460e/paper/basic_training.tex#L695

Should address that the autocorrelation time isn't known beforehand. Which may just be that you know the autocorrelation time for similar systems.

**Comment by davidlmobley** [comment]
Addressed by #111
