### ISSUE TITLE
Missing space before citation.

### ISSUE THREAD

**Issue by mrshirts** [MobleyLab/basic_simulation_training#108]
https://github.com/MobleyLab/basic_simulation_training/blob/924ee8724dca2462c12f6f1dbc287b5f1007460e/paper/basic_training.tex#L730

I would suggest searching for \cite{} and replacing with ~\cite{}. There are a number of other such formatting issues with citations.

**Comment by mrshirts** [comment]
> may be

**Comment by davidlmobley** [comment]
Closed by #111
