### ISSUE TITLE
Make Issues for remaining content to be written?

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/basic_simulation_training#17]
@JIMonroe - any chance you want to create Issues on the tracker for any content which still needs to be written, so we can divvy up tasks among those who want to help?

**Comment by JIMonroe** [comment]
I think I got everything (at least what's currently in the outline as it now stands).  If additional sections are needed, please add them as issues.  Also, if there are any comments or suggestions for changing currently written sections, please also add those as issues so they may be tracked and eventually addressed.
