### ISSUE TITLE
Write "Barostats" section

### ISSUE THREAD

**Issue by JIMonroe** [MobleyLab/basic_simulation_training#19]
This can me modeled after the neatly-organized thermostat section, and should utilize and connect to that section as needed.

**Comment by justinGilmer** [comment]
I can definitely work on this section. Apologies for the radio silence recently! Traveling at the moment but I'll be back this weekend! 

This section was derived from my notes from my undergraduate schooling. Ill start on this, this weekend and put some edits up next week.

**Comment by davidlmobley** [comment]
@justinGilmer - still on track to get something in this week?

**Comment by justinGilmer** [comment]
@davidlmobley  Somehow I missed this notification. But I will have a rough draft of this sometime this week. Two conferences last week and now this week, but I will make sure to get this in!

**Comment by davidlmobley** [comment]
@justinGilmer touching bases on this. One week to go, so if you're not going to have something today or tomorrow let me know so I can block out time in the next week to work on it myself.

**Comment by justinGilmer** [comment]
Sorry about that! Working on this today; will hope to have a pr for review by this evening or tomorrow morning!

**Comment by justinGilmer** [comment]
Finishing this up now. PR in the next few hours.

**Comment by davidlmobley** [comment]
Yay, thanks. And if you finish that and feel like reading more, check out Jacob's open PR.

I'll be trying to do some more writing tomorrow and Thursday myself.

**Comment by davidlmobley** [comment]
This was done.
