### ISSUE TITLE
Write "Integrators" section

### ISSUE THREAD

**Issue by JIMonroe** [MobleyLab/basic_simulation_training#20]
This will incorporate the "stochastic dynamics" section, so that section does not need to be written ( see #15 ).

**Comment by davidlmobley** [comment]
Probably want to note some of Leimkuhler's newer integrators in this section; the Chodera lab has some recent work with these and we've been using some as it seems possible to dramatically improve integration accuracy without much cost in some cases. I believe they have a preprint out by Fass and Chodera.

**Comment by samarjeet** [comment]
I haven't started working on this one yet. I know about the implementation and usage the traditional integrators but haven't looked at Chodera lab's work. If someone else wants to take this one, that would be great. Otherwise I will work on the newer integrators over the weekend and try to write it over the next week.

**Comment by JIMonroe** [comment]
@samerjeet , I can help with this, too.  Do you want to focus on writing up information on traditional integrators and then I can add on a bit for stochastic integrators and more recent work?  I'm not familiar with the Chodera lab work either, but it will be good for me to learn a little bit.  If you want to write it all, I'm happy with that too!

**Comment by JIMonroe** [comment]
@samarjeet , do you want me to take a shot at writing this section?  I'm not sure I'll do a great job, but if you're available to read through and edit I'm willing to put something down.  We essentially have until the end of the week.

**Comment by davidlmobley** [comment]
@JIMonroe - I haven't heard anything from Samarjeet and we have just one week to go. Maybe you want to take a first pass at this?

**Comment by davidlmobley** [comment]
This was added.
