### ISSUE TITLE
Write "Long range electrostatics" section 

### ISSUE THREAD

**Issue by JIMonroe** [MobleyLab/basic_simulation_training#21]
We can either make this a stand-alone section, or go into more detail in the "Classical electrostatics" section.  This is an important issue, so a more detailed discussion of Ewald summations is warranted.  However, we do not want to overlap too much with what is already in "Classical electrostatics" (or some of what is there should be moved to this section).  See #6  for some discussion of this.

**Comment by davidlmobley** [comment]
I could go either way. This one is going to be done by Samarjeet, so maybe we get his input. I've e-mailed him asking for his GitHub ID as I don't have it or if I do, can't find it at the moment.

**Comment by davidlmobley** [comment]
@samarjeet - still thinking to make headway on this soon?

**Comment by samarjeet** [comment]
Yes, I am working on it and I will have it ready by tomorrow. Sorry, I didn't see the previous discussion on this part. I am also including a discussion on the use of IPS for cases when the system can be assumed to isotropic. However, the focus is still on PME and there are a few repetitions of the concepts already mentioned in Classical Electrostatics. We can bring in the changes at the later editing stages once that all the parts of the paper are in.
