### ISSUE TITLE
Check books referenced and make sure we want to endorse

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/basic_simulation_training#23]
We list a lot of books without giving full details; we should give full details and citations.

Additionally, we should make sure that one or more of the authors actually knows and would recommend each of these books; we will be essentially endorsing them so I want to be able to say, "Yes, we really do recommend that; authors ABC and DEF are familiar with it and say it's one of the best books on this topic."

Probably to do that I should list every book by topic here and then get people to put their initials by it if they endorse. Objections?

**Comment by davidlmobley** [comment]
Here are the books referenced; please edit this comment and put your initials next to them if you endorse for the corresponding topic (@samarjeet @hmayes @avisekdas @JIMonroe @justinGilmer @dmzuckerman ) or if for some reason that doesn't work, just comment below and I'll consolidate initials.  **The goal of this is to make sure we do not point people to books that we don't endorse.**

### Overall:
- Allen & Tildesley
- Frenkel, Smit and Geissler (is this now a single book?)
- Tuckermann (he has a book?)

### Classical mechanics
- Goldstein, Poole and Safko

### Thermodynamics
- Atkins PChem
- Zemansky and Dittman

### Stat mech
- Reif
- McQuarrie
- Dill (DLM)
- Hill
- Shell (DLM)
- Zuckerman (DLM)
- Kaznessis

### Classical electrostatics
- Griffiths (DLM)
- Jackson

### Stochastic dynamics (to be merged with anotehr section)
- McQuarrie

### Force fields
- Leach (DLM)
- AMBER manual
- GROMACS manual

### Periodic boundary conditions:
- Leach (DLM)
- Shell 

### Main steps of MD simulation:
- Leach (DLM)

Several sections following these have no books referenced yet.

@dmzuckerman please feel free to note which of these are well-covered by your book, which I do not have in my hands at the moment. :)

**Comment by justinGilmer** [comment]
Could not edit, but here are my recommendations:

## overall
Allen and Tildesley (JBG)

## Stat mech
McQuarrie (JBG)
Thermal Physics by Kittel and Kroemer (JBG)

## Thermodynamics
McQuarrie (JBG) 
If I recall correctly, McQuarrie also provided a treatment for themo as well. This was the book we used in my undergrad classes.

Thermal Physics by Kittel and Kroemer (JBG)

**Comment by samarjeet** [comment]
I have used this book "Numerical Simulation in Molecular Dynamics : Numerics, Algorithms, Parallelization, Applications" by Michael Griebel, Gerhard Zumbusch, Stephan Knapek. I would definitely endorse it as I have used it heavily in writing my sections.

**Comment by davidlmobley** [comment]
@hmayes - did you have any input on the book list above?

**Comment by davidlmobley** [comment]
I think we have most of these in already, @hmayes !

**Comment by davidlmobley** [comment]
Marking this as closed because I think I have people's recommendations above, and I brought all the references in in #44 I believe.
