### ISSUE TITLE
Add bullet points at beginnings of sections

### ISSUE THREAD

**Issue by JIMonroe** [MobleyLab/basic_simulation_training#34]
We can do this at the end after we have all of our ideas down.  These should clearly express key ideas and topics that should be gleaned from the associated text.

**Comment by davidlmobley** [comment]
I am not actually sure we want to do this, or at least, we should probably do it only where it makes particular sense (some sections do not seem to lend themselves to this). Do you have an example where you think it will really help?

**Comment by JIMonroe** [comment]
I'm neither for nor against the bullet points in general.  Overall, though, I would argue for consistency, though it looks like we're moving towards getting rid of most of them in the more recent versions.

I'm going to close this and just let things evolve as needed.
