### ISSUE TITLE
Should I add more refs in general?

### ISSUE THREAD

**Issue by hmayes** [MobleyLab/basic_simulation_training#41]
Hello all! I'm beginning to read through everyone's contributions and edit as I go. My first impression is that this is far fewer refs that I would use. For example, when we say that MD is a key tool, I'd reference some reviews that give examples to back up this statement.

Is there any reason we want to limit refs (e.g. not overwhelm students), or should I start adding? Of course, my additional will be reviewed when I do a pull, but I don't want to waste my time if this is not a common feeling.

Thanks in advance for your feedback.
-Heather

**Comment by davidlmobley** [comment]
Please start adding, @hmayes ! I think we probably want to walk a middle ground though between:
a) Add a ton of references like a review, where some of the references might perhaps only be tangential, and
b) Add a few references where each is extremely helpful

We probably want to ensure every reference is indeed quite helpful and NOT have a ton, e.g. that each one is actually really worth reading.

**Comment by hmayes** [comment]
Thanks for the feedback! I'll be selective.
