### ISSUE TITLE
Thermostat naming

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/basic_simulation_training#50]
@justinGilmer @JIMonroe : @EfremBraun pointed this out:
> EB: I recommend referring to this thermostat as the Gaussian Thermostat. I’ve seen it referred to as the Hoover-Evans thermostat as well (I haven’t seen it called the Hoover thermostat, but I’m sure somebody has called it that), but simply calling it the Gaussian thermostat avoids wading into the argument about who came up with it first.

OK with calling what we currently call the ``Hoover thermostat`` the Gaussian thermostat? I don't think I've heard it called just ``Hoover`` so I will make this change unless there are objections.

**Comment by justinGilmer** [comment]
Yeah, Gaussian is fine with me. Its a bit more descriptive as well.

**Comment by EfremBraun** [comment]
I'll make this change in an upcoming pull request (I'll send it in a few hours).

**Comment by EfremBraun** [comment]
Oops, that works too.

**Comment by davidlmobley** [comment]
I've just got this into my open PR that I'm working on, @EfremBraun . So maybe your new PR can build off of mine (#44 ).

I hope to finish in the next hour.
