### ISSUE TITLE
Deal with remaining to-do items

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/basic_simulation_training#52]
There are various to-do items in the text; I could use people's help working through them.

(And feel free to also add more when you see things that need doing.)

**Comment by JIMonroe** [comment]
We're really close!

What time is our deadline tomorrow and are we expecting to finish all todos by then?

**Comment by hmayes** [comment]
Yes, how much more time do we have??

**Comment by davidlmobley** [comment]
I'm trying to figure that out. Basically I THINK I have to submit while my finance person is still in the office (since I have to use her corporate card), which means likely before 4 or 5 pm Pacific.  I'd be more comfortable, though, if we could submit really late tonight. So maybe I'll touch bases with Michael and see if he could accept a submission first thing in the morning. 

I do have a reasonable amount of time to work on it today, sort of on and off. And I write fairly fast, so as long as @samarjeet gets his stuff in and you all help me edit, I THINK we are going to be in fairly good shape.

@justinGilmer time to help with final edits and to-dos today?

**Comment by justinGilmer** [comment]
Yeah I will be available off and on today. Just printed out the master branch version and am going to read through the whole thing now.

**Comment by davidlmobley** [comment]
@dmzuckerman - we're getting ready to submit today or tomorrow am if you want to do a read-through at all. It's a bit rough in places and we're waiting on one significant revision, but would love any edits.

**Comment by hmayes** [comment]
I'm on Europe time, so if we have until tomorrow morning, I can do a read
through in my morning (9 hrs ahead of Irvine CA), allowing me to read
through things added tonight.

**Comment by davidlmobley** [comment]
Closed by #76
