### ISSUE TITLE
Figure additions?

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/basic_simulation_training#59]
We could really use more figures. Not sure how much headway I can make on that today, but at least we can brainstorm here about figures we ought to have eventually, and perhaps work some on them while this is in review.

Ideas:
- Figure (cartoon) showing the terms in a typical potential energy function and what they mean
- Cartoons illustrating equilibration (?) and convergence (?)
- ...?

**Comment by hmayes** [comment]
I can take a stab at the first one unless anyone else has started on
that....

**Comment by davidlmobley** [comment]
Sounds great. Um, do you have Keynote? I have some old slides that perhaps could be reused if you like.

**Comment by hmayes** [comment]
I do! Thanks!

**Comment by davidlmobley** [comment]
One sec.

**Comment by davidlmobley** [comment]
OK, so there are some cartoonish graphics on side 6 here that you are welcome to use/adapt/trash depending on whether you like them or not: https://drive.google.com/file/d/0B5sFkoaaNUxtbXRUUVVPYWEtdG8/view?usp=sharing

**Comment by JIMonroe** [comment]
![equilibration_fig](https://user-images.githubusercontent.com/7297977/43555588-eb7f33fa-95af-11e8-8c23-6891659143c8.png)

For the equilibration illustration, were you thinking something like this?

**Comment by davidlmobley** [comment]
Something like that would be helpful, yes.

**Comment by davidlmobley** [comment]
(General thought being that we want warning bells to go off in someone's head if they see a curve which is changing still systematically as a function of time at the end of "equilibration")

**Comment by davidlmobley** [comment]
OK, resolved by #73 and #74, thanks!
