### ISSUE TITLE
Revisions

### ISSUE THREAD

**Issue by EfremBraun** [MobleyLab/basic_simulation_training#63]
Hard to make changes with the rapid-fire edits, so here are some I'd like to suggest:

Section 3.3.1: There are a few things that confuse me here.

> Traditional discussions of classical statistical mechanics, especially concise ones, tend to focus first or primarily on macroscopic thermodynamics and microscopic \emph{equilibrium} behavior based on the Boltzmann factor, which tells us that configurations $\conf$ occur with (relative) probability $\exp[-U(\conf)/k_B T]$, based on potential energy function $U$ and temperature $T$ in Kelvin units.
Dynamical phenomena and their connection to equilibrium tend to be treated later in discussion, if at all.
But in both fundamental and practical ways, this ordering is wrong.
Think Arrhenius first, then Boltzmann.

I think this is phrased a little too strongly for a philosophical point. I do understand the point about nature only "knowing" dynamics, which then happens to give rise to statistical mechanics, but I feel a little unease about saying that it's wrong to think about statistical mechanics prior to thinking about dynamics.

> MD simulation, like nature itself, runs dynamics.
Any equilibrium phenomena may (or may not) occur as a consequence and equilibrium behavior is hardly automatic~\cite{Zuckerman:2010:}.
In fact, based on current and foreseeable computational technology, it is much safer to assume that your simulation will not exhibit equilibrium behavior.
However, an MD simulation is guaranteed to exhibit dynamical behavior.

We haven't really defined "equilibrium behavior," so it's hard to say that the simulation will not exhibit it. For people doing simple liquid-phase simulations (not proteins), I'm pretty sure they're able to get to equilibrium.

> A final essential topic is the difference between equilibrium and non-equilibrium systems.
We noted above that an MD trajectory is not likely to represent the equilibrium ensemble because the trajectory is probably too short.
However, in a living cell where there is no shortage of time, biomolecules may exhibit non-equilibrium behavior for a quite different reason -- because they are \emph{driven} by the continual addition and removal of (possibly energy-carrying) substrate and product molecules.
In this type of non-equilibrium situation, the distribution of configurations will not follow a Boltzmann factor distribution.
Specialized simulation approaches are available to study such systems~\cite{Chong:2017:CurrentOpinioninStructuralBiology,  Zuckerman:2017:AnnuRevBiophys} but they are not beginner-friendly.
Non-equilibrium molecular concepts pertinent to cell biology have been discussed at an introductory level (e.g. \url{http://www.physicallensonthecell.org/}).

We haven't mentioned the different between equilibrium simulations and non-equilibrium simulations. Should we? If a beginner wants to simulate a Fickian diffusion coefficient, the impulse is to set up a non-equilibrium concentration gradient and measure the flux, when it's usually better to run an equilibrium simulation and get the diffusion coefficient from an autocorrelation function.

Other more minor things:

> In classical molecular simulations, atoms are typically represented by sites bearing charge in units of fractions of an elementary charge, so atom-atom interactions are thus necessarily long range compared to other interactions in these systems (which fall off a $1/r^3$ or faster).

The second part of this sentence does not follow from the first.

> For example, the AMBER family force fields usually reduce 1-4 electrostatics to $\frac{1}{1.2}$ of their original value,

Is that right?

> Thus, starting velocities must be assigned; usually this is done by assigning random initial velocities to atoms in a way such that the correct Maxwell-Boltzmann distribution at the desired temperature is achieved as a starting point.

Might want to add, "The actual assignment process is typically unimportant, as the Maxwell-Boltzmann distribution will quickly arise naturally from the equations of motion. Since the momentum of the center-of-mass of the simulation box is conserved by Newtonian dynamics, the last particle is typically assigned a velocity to guarantee that the center-of-mass momentum is 0, preventing the simulation box from drifting."

> such as a switch from NVT to NPT

Should be reversed. "from NPT to NVT" is more typical.

Section 4.5.3: I recommend getting rid of the subparagraphs for each of the three barostats since ther groupings are somewhat arbitrary (I might argue that the volume-rescaling, Berendsen, and MC barostats are all examples of volume-rescaling barostats). Is the volume-rescaling barostat in the first paragraph an actual example of a barostat, or does it just describe a technique the barostats used? It seems like the latter, in which case it's out of place.

Section 4.7: Not reading this for now since it looks like there are changes coming.

Another suggestion I have is to include in the checklist at the end something along the lines of "Choose a force field" and "Ensure that your force field is correctly implemented by replicating energies/forces/results from other papers that used it."

**Comment by davidlmobley** [comment]
@EfremBraun on the stat mech material no one is touching it at present so you are free to edit away.

> I think this is phrased a little too strongly for a philosophical point. I do understand the point about nature only "knowing" dynamics, which then happens to give rise to statistical mechanics, but I feel a little unease about saying that it's wrong to think about statistical mechanics prior to thinking about dynamics.

I think I am inclined to agree with you; feel free to propose an edit. 

> We haven't really defined "equilibrium behavior," so it's hard to say that the simulation will not exhibit it. For people doing simple liquid-phase simulations (not proteins), I'm pretty sure they're able to get to equilibrium.

Likewise, I agree with you. I think Zuckerman (who wrote this) is mainly thinking about biomolecular simulations, but our topic is broader so we should temper the language.

> Section 4.5.3: I recommend getting rid of the subparagraphs for each of the three barostats since ther groupings are somewhat arbitrary (I might argue that the volume-rescaling, Berendsen, and MC barostats are all examples of volume-rescaling barostats). Is the volume-rescaling barostat in the first paragraph an actual example of a barostat, or does it just describe a technique the barostats used? It seems like the latter, in which case it's out of place.

Fine with me.
