### ISSUE TITLE
Two things I'm not sure about

### ISSUE THREAD

**Issue by EfremBraun** [MobleyLab/basic_simulation_training#68]
> A final essential topic is the difference between equilibrium and non-equilibrium systems.
We noted above that an MD trajectory is not likely to represent the equilibrium ensemble because the trajectory is probably too short.
However, in a living cell where there is no shortage of time, biomolecules may exhibit non-equilibrium behavior for a quite different reason -- because they are \emph{driven} by the continual addition and removal of (possibly energy-carrying) substrate and product molecules.
In this type of non-equilibrium situation, the distribution of configurations will not follow a Boltzmann factor distribution.
Specialized simulation approaches are available to study such systems~\cite{Chong:2017:CurrentOpinioninStructuralBiology,  Zuckerman:2017:AnnuRevBiophys} but they are not beginner-friendly.
Non-equilibrium molecular concepts pertinent to cell biology have been discussed at an introductory level (e.g. \url{http://www.physicallensonthecell.org/}).

We haven't mentioned the different between equilibrium simulations and non-equilibrium simulations. Should we? If a beginner wants to simulate a Fickian diffusion coefficient, the impulse is to set up a non-equilibrium concentration gradient and measure the flux, when it's usually better to run an equilibrium simulation and get the diffusion coefficient from an autocorrelation function.

> For example, the AMBER family force fields usually reduce 1-4 electrostatics to $\frac{1}{1.2}$ of their original value,

Is that right?

**Comment by JIMonroe** [comment]
Yes, the 1-4 interaction thing is right.  For LJ terms, the 1-4 reduction is 1/2, and for electrostatics it's 1/1.2.  Unfortunately, all force fields generally treat 1-4 interactions differently.

**Comment by davidlmobley** [comment]
> We haven't mentioned the different between equilibrium simulations and non-equilibrium simulations. Should we? If a beginner wants to simulate a Fickian diffusion coefficient, the impulse is to set up a non-equilibrium concentration gradient and measure the flux, when it's usually better to run an equilibrium simulation and get the diffusion coefficient from an autocorrelation function.

I think what you're getting at here (the best ways of calculating specific properties) might be outside the scope of this work; there will be (or we hope there will be) SEPARATE best practices documents on  how to do various different kinds/types of calculations, e.g. one might imagine a best practices document on "calculation of transport properties", "calculation of diffusion coefficients" (?) etc. So trying to address "how to calculate X or Y" is mostly outside the scope of this paper; this one is meant to be sort of foundational for all of the others -- things we are going to assume people understand before they even begin looking at how to calculate a specific property of interest.

That said, the distinction between equilibrium and non-equilibrium simulations IS very important so if there's something specific you think we should say about it that we haven't, please have at it, @EfremBraun .
