### ISSUE TITLE
Add source materials for figures

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/basic_simulation_training#77]
@JIMonroe @hmayes can you add the source materials for the figures you recently added in case we ever want to update them?

**Comment by davidlmobley** [comment]
Heather's was added by #75

**Comment by JIMonroe** [comment]
I know you've already submitted, but I've just added the python script I used to generate the figure.  No changes to the text or pdf.

**Comment by davidlmobley** [comment]
Perfect, thanks! (And yes, adding things here after submission is perfectly reasonable; this will be an ongoing process.)
