### ISSUE TITLE
Url not wrapping properly

### ISSUE THREAD

**Issue by justinGilmer** [MobleyLab/basic_simulation_training#8]
https://github.com/MobleyLab/basic_simulation_training/blob/896f3eb55a6e2d1d6b2dbffcfd981a9d308d79d8/paper/basic_training.tex#L196

For this url and the one below it, it is not properly wrapping to the next line in the pdf.

[This](https://tex.stackexchange.com/questions/3033/forcing-linebreaks-in-url) might be a solution to our problem, however, I have not had time to verify. Once I submit the thermostat PR, I can take a look at this.

**Comment by davidlmobley** [comment]
Closed by #22 .
