### ISSUE TITLE
Submit paper

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/basic_simulation_training#83]
Barring any notification from @hmayes , @samarjeet , @JIMonroe @justinGilmer or @EfremBraun in the next couple minutes that something is still pending, I'm going to attempt to submit by 9 am once I get one last PR merged.

**Comment by davidlmobley** [comment]
Thanks, everyone, for all the help on this! It was great seeing everything come together in the last couple days. :)

**Comment by justinGilmer** [comment]
Awesome! Congratulations everyone!

**Comment by hmayes** [comment]
Thank you all!!

**Comment by davidlmobley** [comment]
OK, it's off!! Roughly the easiest submission process ever; nowhere near as many boxes to fill in as normal. :)

**Comment by samarjeet** [comment]
Perfect !! Thanks everyone :)

**Comment by hmayes** [comment]
Nice!!
