### ISSUE TITLE
Create tagged version with a release once accepted

### ISSUE THREAD

**Issue by justinGilmer** [MobleyLab/basic_simulation_training#87]
We should tag this version once it has been accepted into the journal. Will allow us to create a something that can be fetched by git, and we can generate a compressed file archive of the repo at this state.

**Comment by justinGilmer** [comment]
https://help.github.com/articles/creating-releases/

**Comment by davidlmobley** [comment]
Yes, exactly.

We should perhaps create a release of the submitted version. Or maybe a "v1.0 pre-release" or something.

**Comment by justinGilmer** [comment]
Agreed. I think all collaborators can do this, but it might just be the repository owner. 

I am not too sure. The repo's where I have done this have all been through one's where I have ownership. 

I think it would be nice to archive the paper along the way. Pre-release sounds like a great plan. 

then we can create a new tag and release for the accepted manuscript

**Comment by justinGilmer** [comment]
@davidlmobley I've created a release that has been marked as a pre-release. 

If you think it seems ok, feel free to publish it as our first release.

**Comment by davidlmobley** [comment]
Published the pre-release, thanks.

**Comment by davidlmobley** [comment]
Closing this; I also just created a release for the published version.
