### ISSUE TITLE
Latex Makefile for proper compilation?

### ISSUE THREAD

**Issue by justinGilmer** [MobleyLab/basic_simulation_training#9]
Coming from someone who is a bit less tex and latex savvy, it might be useful to create a very barebones latex makefile for this paper. Im able to compile on my machine, but there are many errors abound and im not sure if my PDF version is exactly correct. that or even just a script for the compilation of the paper could be very useful as we are finalizing this paper throughout the day.

**Comment by davidlmobley** [comment]
Haha, I'm on the opposite end of this -- if I see a makefile I think "Oh, no, this is going to be complex to compile!". I usually use:
- TeXShop on my Mac, or
- Overleaf
and both of these work seamlessly in general, e.g. in Overleaf it just compiles automatically and "just works" and on my Mac, I just click "compile" and it compiles.

**Comment by justinGilmer** [comment]
Fair point :). I realize now, that the errors I was getting seem to be warnings. I think they are the overflowing urls I mentioned in #8 . I was able to ignore and still produce the pdf. 

This makes a bit more sense now. So I will close this issue.
