### ISSUE TITLE
Peer reviews are in; need to deal with them ASAP

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/basic_simulation_training#91]
Peer reviews came in (late) on Oct. 10 but apparently there was an e-mail glitch with the system so I was never notified. I've just retrieved them and am posting here. *We need to rush and get the paper revised* so we don't hold up the first issue or get left behind.

The main text of the comments is high-level , but one of the reviewers provided a marked up PDF file: 
[marked up PDF file](https://github.com/MobleyLab/basic_simulation_training/files/2544580/13412-anonymized-attachment-for-review-129153.pdf) which we need to pull comments from or deal with.  The reviewer did note: 
>Some of the wording suggestions are perhaps a matter of taste, so take or leave them as you wish. 

If one of the co-authors has a moment to pull these and either address or (if they require more work) turn them into issues on the issue tracker that would be awesome, as I'm swamped at present and I don't want to be the bottleneck. 

We should also take care of #89 and possibly #71 at the same time. And we also need to update to the latest LiveCoMS template. 

Here is the full text of the other parts of the reviews, which are responses to a series of questions. *Basically there is nothing to address* and it is all positive. I'm grouping the Reviewer 1 (R1) and Reviewer 2 (R2) comments together by question.

Q: What is the level of significance of this work and its suitability for the journal? Is it likely to have a strong positive impact on the targeted set of readers? If this is a revision, what is the significance of the updated material?

>R1: This best practices guide is a comprehensive compilation of concepts underlying MD simulations. The authors highlight the many different ways some of these concepts can be implemented in practice in the available MD engines. This review will be a good starting point for beginners to understand implications of deciding ensembles, thermostats, timesteps etc. on the results they will eventually obtain from simulation data.
>R1: In particular, the discussion on thermostats and barostats is impressive.
>
>R2: It is highly significant, and an essential starting point for the journal.

Q: To what extent does the article engage with current understanding in the scholarly community? If this is a revision, to what extent do the authors engage with the community participating on their GitHub version?

>R1: In my opinion, the checklist will become essential before starting MD simulations on new systems. 
>
>R2: It reflects the current broader understanding well. More specialized issues are beyond the scope of the document.

Q: In what ways should the paper be improved to be easy to read, free from grammatical errors, have a professional presentation, and meet the article formatting guidelines laid out in the author policies (at https://livecomsjournal.github.io/authors/policies/)?

> R1: Manuscript is clear and to the point.
>
>R2:  I have given suggestions for minor rewordings/corrections in the attached pdf file. There are also a few other more substantive (but still relatively minor) comments for improvement. This should be read with Adobe Reader (or equivalent) to view the comments.

Q: How does the article address the specific reviewer criteria for the article type (Perpetual Reviews, Tutorials, Comparisons of Computational Software, and Lessons Learned), as described at https://livecomsjournal.github.io/policies/reviewer_information/?

> R1: This is well-suited for a Best Practices article.
> 
> R2: It is a good baseline for this goals of the journal.

Q: Do you have additional comments for the author?

> R1: No
> 
> R2: Some of the wording suggestions are perhaps a matter of taste, so take or leave them as you wish.

**Comment by hmayes** [comment]
For the comment: "If one of the co-authors has a moment to pull these and either address or (if they require more work) turn them into issues on the issue tracker that would be awesome". I just did this, adding the issues I did not resolve to issue #89, and addressed many of those issues. Pull request to follow....

**Comment by dmzuckerman** [comment]
Great to see the positive reviews.  I read through the commented pdf and did not see any suggestions for my section.  Please just let me know how I can help.
